categories:
  - title: 'ğŸŒ± Growth Pod'
    labels:
      - 'Growth'
  - title: 'ğŸ’³ Credit Card Pod'
    labels:
      - 'Credit Card'
  - title: 'ğŸ› Spend Pod'
    labels:
      - 'Spend'
  - title: 'ğŸ›  Platform Pod'
    labels:
      -  'Platform'
  - title: 'ğŸ“ˆ Invest/Borrow Pod'
    labels:
      - 'Invest'
      - 'Borrow'
  - title: 'Tech Debt/CI Improvements'
    labels:
      - 'Tech Debt'
template: $CHANGES
